# linku 配置（自动生成）
config_version = 1

[[links]]
link = "C:\\Users\\30902\\AppData\\Local\\MangaJaNaiConverterGui"
target = "D:\\1SoftLink\\AppData\\Local\\MangaJaNaiConverterGui"
type = "目录"
created_at = "2025-08-26T08:07:56.443564+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Roaming\\XnViewMP"
target = "D:\\1SoftLink\\AppData\\Roaming\\XnViewMP"
type = "目录"
created_at = "2025-08-26T08:10:21.316273+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Local\\Microsoft\\Edge"
target = "D:\\1SoftLink\\AppData\\Microsoft\\Edge"
type = "目录"
created_at = "2025-08-26T08:14:47.615413+00:00"

[[links]]
link = "C:\\Users\\30902\\Taskfile.yml"
target = "D:\\1VSCODE\\Projects\\LazyCommand\\EnvU\\dotfile\\Taskfile.yml"
type = "文件"
created_at = "2025-08-26T08:59:37.834777+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Local\\kingsoft"
target = "D:\\1SoftLink\\AppData\\Local\\kingsoft"
type = "目录"
created_at = "2025-09-21T16:18:48.033558+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Local\\Czkawka"
target = "D:\\1SoftLink\\AppData\\Local\\Czkawka"
type = "目录"
created_at = "2025-10-01T18:19:55.766886+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Roaming\\exhentai-manga-manager"
target = "D:\\1SoftLink\\AppData\\Roaming\\exhentai-manga-manager"
type = "目录"
created_at = "2025-10-07T21:24:25.780764+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Local\\Qarmin"
target = "D:\\1SoftLink\\AppData\\Local\\Qarmin"
type = "目录"
created_at = "2025-10-11T11:01:27.688081+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Roaming\\Adobe"
target = "D:\\1SoftLink\\AppData\\Roaming\\Adobe"
type = "目录"
created_at = "2025-10-17T13:53:08.468000+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Local\\oh-my-posh"
target = "D:\\1SoftLink\\AppData\\Local\\oh-my-posh"
type = "目录"
created_at = "2025-10-21T15:20:32.168220+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Roaming\\uTools"
target = "D:\\1SoftLink\\AppData\\Roaming\\uTools"
type = "目录"
created_at = "2025-10-25T16:03:04.528916+00:00"

[[links]]
link = "C:\\ProgramData\\Netease\\GameViewer"
target = "D:\\1SoftLink\\ProgramData\\Netease\\GameViewer"
type = "目录"
created_at = "2025-10-30T03:14:53.165626+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Roaming\\Cursor"
target = "D:\\1SoftLink\\AppData\\Roaming\\Cursor"
type = "目录"
created_at = "2025-11-23T12:37:30.783794+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Roaming\\DigitalVolcano\\DuplicateCleaner"
target = "D:\\1SoftLink\\AppData\\Roaming\\DigitalVolcano\\DuplicateCleaner"
type = "目录"
created_at = "2025-11-23T12:38:27.476858+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Local\\Zed"
target = "D:\\1SoftLink\\AppData\\Local\\Zed"
type = "目录"
created_at = "2025-11-23T15:06:27.687194+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Local\\Programs\\Ollama"
target = "D:\\1SoftLink\\AppData\\Local\\Programs\\Ollama"
type = "目录"
created_at = "2025-12-07T23:20:58.916530+00:00"

[[links]]
link = "C:\\Users\\30902\\.ollama"
target = "D:\\1Repo\\Soft\\ollama\\.ollama"
type = "目录"
created_at = "2025-12-08T06:07:03.333505+00:00"

[[links]]
link = "C:\\Users\\30902\\.gemini"
target = "D:\\1SoftLink\\Users\\30902\\.gemini"
type = "目录"
created_at = "2025-12-14T04:00:03.988921+00:00"

[[links]]
link = "C:\\Users\\30902\\AppData\\Roaming\\Kiro"
target = "D:\\1SoftLink\\AppData\\Roaming\\Kiro"
type = "目录"
created_at = "2025-12-23T08:54:34.122919+00:00"

[[links]]
link = "C:\\Users\\30902\\.iflow"
target = "D:\\1SoftLink\\Users\\30902\\.iflow"
type = "目录"
created_at = "2025-12-23T08:56:40.272098+00:00"
